<?xml version="1.0" encoding="UTF-8"?>
<!--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Legal Notices

S.W.I.F.T. SC © 2026. All rights reserved.

This schema is a component of MyStandards, the Swift collaborative Web application used to manage standards definitions and industry usage.

This is a licensed product, which may only be used and distributed in accordance with MyStandards License	Terms as specified in MyStandards Service Description and the related Terms of Use.

Unless otherwise agreed in writing with S.W.I.F.T. SC, the user has no right to:
 - authorise external end users to use this component for other purposes than their internal use.
 - remove, alter, cover, obfuscate or cancel from view any copyright or other proprietary rights notices appearing in this physical medium.
 - re-sell or authorise another party e.g. software and service providers, to re-sell this component.

This component is provided 'AS IS'. Swift does not give and excludes any express or implied warranties with respect to this component such as but not limited to any guarantee as to its quality, supply or availability.

Any and all rights, including title, ownership rights, copyright, trademark, patents, and any other intellectual property rights of whatever nature in this component will remain the exclusive property of Swift or its licensors.

Trademarks and Patents
Swift is the trade name of S.W.I.F.T. SC.
The following are registered trademarks of Swift: 3SKey, Innotribe, MyStandards, Sibos, Swift, SwiftNet, the Standards Forum logo, the Swiftlogo, Swift GPI with logo, the Swift GPI logo, and UETR.
Other product, service, or company names in this publication are trade names, trademarks, or registered trademarks of their respective owners.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


Group: Cross Border Payments and Reporting Plus (CBPR+)
Collection: CBPRPlus SR2026 (Combined)
Usage Guideline: CBPRPlus-camt.025.001.08_Receipt
Base Message: camt.025.001.08
Date of publication: 20 February 2026
URL: https://www2.swift.com/mystandards/#/mp/mx/__u9nUAWPEfC0rITL7a8sCA/_AXr1SAWQEfC0rITL7a8sCA
Description: Scope
The Receipt message is sent by a message recipient to the message sender. It is sent to acknowledge the receipt of one or multiple messages sent previously.
The Receipt message is an application receipt acknowledgement and conveys information about the processing of the original message(s).
Usage
The Receipt message is used when the exchange of messages takes place in an asynchronous manner.
This may happen, for instance, when an action is requested from the message sender (a deletion, modification or cancellation). The message sender will first acknowledge the request (with a Receipt message) and then execute it.
The message can contain information based on the following elements: reference of the message(s) it acknowledges, the status code (optional) and further explanation:
- reference of the message it acknowledges
- potentially, a status code and status reason information.
Generated by the MyStandards web platform [https://www.swift.com/mystandards] on 2026-05-21T06:43:37Z
-->
<xs:schema xmlns="urn:iso:std:iso:20022:tech:xsd:camt.025.001.08" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:iso:std:iso:20022:tech:xsd:camt.025.001.08">
    <xs:element name="Document" type="Document"/>
    <xs:simpleType name="CBPR_DateTime">
        <xs:restriction base="xs:dateTime">
            <xs:pattern value=".*(\+|-)((0[0-9])|(1[0-4])):[0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CBPR_RestrictedFINXMax105Text">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z/\-\?:\(\)\.,'\+ ]+"/>
            <xs:minLength value="1"/>
            <xs:maxLength value="105"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="CBPR_RestrictedFINXMax35Text">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z/\-\?:\(\)\.,'\+ ]+"/>
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Document">
        <xs:sequence>
            <xs:element name="Rct" type="ReceiptV08"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ExternalRequestStatus1Code">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="4"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ExternalStatusReason1Code">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="4"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="MessageHeader9__1">
        <xs:sequence>
            <xs:element name="MsgId" type="CBPR_RestrictedFINXMax35Text"/>
            <xs:element name="CreDtTm" type="CBPR_DateTime"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OriginalMessageAndIssuer1__1">
        <xs:sequence>
            <xs:element name="MsgId" type="CBPR_RestrictedFINXMax35Text"/>
            <xs:element name="MsgNmId" type="CBPR_RestrictedFINXMax35Text"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Receipt6__1">
        <xs:sequence>
            <xs:element name="OrgnlMsgId" type="OriginalMessageAndIssuer1__1"/>
            <xs:element name="ReqHdlg" type="RequestHandling3__1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ReceiptV08">
        <xs:sequence>
            <xs:element name="MsgHdr" type="MessageHeader9__1"/>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="RctDtls" type="Receipt6__1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RequestHandling3__1">
        <xs:sequence>
            <xs:element name="Sts" type="RequestStatus1Choice__1"/>
            <xs:element maxOccurs="1" minOccurs="0" name="StsRsn" type="StatusReasonInformation14__1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RequestStatus1Choice__1">
        <xs:choice>
            <xs:element name="Cd" type="ExternalRequestStatus1Code"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="StatusReason6Choice__1">
        <xs:choice>
            <xs:element name="Cd" type="ExternalStatusReason1Code"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="StatusReasonInformation14__1">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="Rsn" type="StatusReason6Choice__1"/>
            <xs:element maxOccurs="2" minOccurs="0" name="AddtlInf" type="CBPR_RestrictedFINXMax105Text"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
